name: Keep Render Server Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render servers
        run: |
          # YouTube Tool server
          yt_response=$(curl -s -o /dev/null -w "%{http_code}" https://mcp-puch-80eg.onrender.com/mcp/)
          echo "Pinged YouTube Tool server, received status code: $yt_response"
          if [ "$yt_response" -ne 200 ]; then
            echo "Server (YouTube Tool) might be down!"
          fi

          # Music Memes server
          mm_response=$(curl -s -o /dev/null -w "%{http_code}" https://emceepee-music-memes.onrender.com/mcp/)
          echo "Pinged Music Memes server, received status code: $mm_response"
          if [ "$mm_response" -ne 200 ]; then
            echo "Server (Music Memes Tool) might be down!"
          fi
