name: Keep Render Server Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render server
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" YOUR_RENDER_URL_HERE/mcp)
          echo "Pinged server, received status code: $response"
          if [ "$response" -ne 200 ]; then
            echo "Server might be down!"
            # Optionally, you can add more actions here, like sending a notification.
          fi
